name    'ramiel-owncloud'
version '0.1.0'
source 'https://github.com/ramiel/puppet-owncloud'
author 'Fabrizio Ruggeri @3logic'
license 'Apache License, Version 2.0'
summary 'Owncloud install module'
description 'Make sure owncloud is configured and installed correctly on different environments'
project_page 'https://github.com/ramiel/puppet-owncloud'

## Add dependencies, if any:
dependency 'jfryman/nginx', '>= 0.0.1'
